# Data Analysis on Student Performance Analysis

## Notebook 2 - Exploratory Data Analysis (EDA)

**Author:** Junhyuk Lee

**Date:** April 6, 2026

## Contents

- Abstract
- Imports
- EDA - Descriptive Analysis
- EDA - Univariate Analysis
- EDA - Bivariate Analysis

---

## Abstract

In this notebook, we will perform Exploratory Data Analysis (EDA) to uncover patterns, detect anomalies, and generate insights from the Students Performance dataset, which has been processed and cleaned in `01_preprocessing.ipynb`.

The notebook includes univariate and multivariate analysis using statistical summaries and visualizations. The goal is to understand the data better in preparation for our data analysis.

---

## Imports

In [10]:
import numpy as np
import pandas as pd

# Data Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Suppress warning messages
import warnings
warnings.filterwarnings("ignore")

---

## EDA - Descriptive Analysis

Let's explore our data set to get a better understanding of our dataset.

In [14]:
# Reading in the dataset
students = pd.read_csv("../data/processed/students_cleaned.csv")

Recall our dataset `students`:

In [16]:
students.head()

,student_id,age,gender,country,major,university_year,GPA,study_hours_per_day,class_attendance_percent,sleep_hours,...,internet_quality,mental_stress_level,AI_tool_usage_hours,favorite_AI_tool,note_taking_method,exam_preparation_days,coffee_consumption_per_day,extracurricular_hours_per_week,final_exam_score,assignment_score
0,S00001,23,Female,Germany,Law,4,3.81,4.2,96,6.2,...,Average,4.8,1.5,Claude,Digital,15,3,7.6,100,100
1,S00002,26,Female,USA,Economics,2,3.46,3.3,94,6.6,...,Average,3.9,2.3,Gemini,Mixed,11,3,5.2,100,83
2,S00003,18,Female,Canada,Medicine,3,4.00,4.5,100,6.3,...,Average,4.8,0.0,No tools,Mixed,12,3,4.6,100,100
3,S00004,20,Male,Australia,Physics,4,3.77,5.8,97,7.1,...,Good,5.9,2.9,Gemini,Mixed,11,1,4.0,100,98
4,S00005,28,Female,Australia,Medicine,2,4.00,3.1,96,8.4,...,Good,3.1,1.5,ChatGPT,Handwritten,15,4,1.4,100,94

In [17]:
students.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 27 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   student_id                      10000 non-null  object
 1   age                             10000 non-null  int64
 2   gender                          10000 non-null  object
 3   country                         10000 non-null  object
 4   major                           10000 non-null  object
 5   university_year                 10000 non-null  int64
 6   GPA                             10000 non-null  float64
 7   study_hours_per_day             10000 non-null  float64
 8   class_attendance_percent        10000 non-null  int64
 9   sleep_hours                     10000 non-null  float64
 10  screen_time_hours               10000 non-null  float64
 11  social_media_hours              10000 non-null  float64
 12  gaming_hours                    10000 non-null  float64
 13  exercise_hours_per_week         10000 non-null  float64
 14  part_time_job                   10000 non-null  object
 15  relationship_status             10000 non-null  object
 16  family_income_level             10000 non-null  object
 17  internet_quality                10000 non-null  object
 18  mental_stress_level             10000 non-null  float64
 19  AI_tool_usage_hours             10000 non-null  float64
 20  favorite_AI_tool                10000 non-null  object
 21  note_taking_method              10000 non-null  object
 22  exam_preparation_days           10000 non-null  int64
 23  coffee_consumption_per_day      10000 non-null  int64
 24  extracurricular_hours_per_week  10000 non-null  float64
 25  final_exam_score                10000 non-null  int64
 26  assignment_score                10000 non-null  int64
dtypes: float64(10), int64(7), object(10)
memory usage: 2.1+ MB

We'll start by using the `df.describe()` method to generate a statistical summary of our dataset, rounding it to three decimal places.

This includes the **mean**, the **median**, **max** and **min** values, as well as **standard deviation**.

In [19]:
students.describe().round(3)

,age,university_year,GPA,study_hours_per_day,class_attendance_percent,sleep_hours,screen_time_hours,social_media_hours,gaming_hours,exercise_hours_per_week,mental_stress_level,AI_tool_usage_hours,exam_preparation_days,coffee_consumption_per_day,extracurricular_hours_per_week,final_exam_score,assignment_score
count,10000.000,10000.000,10000.000,10000.000,10000.000,10000.000,10000.000,10000.000,10000.000,10000.000,10000.000,10000.000,10000.000,10000.000,10000.000,10000.000,10000.000
mean,22.953,2.510,3.618,3.509,90.488,7.014,5.790,2.798,1.580,3.074,4.055,1.255,12.045,1.798,4.020,96.054,92.960
std,3.159,1.124,0.395,1.474,9.953,1.192,1.882,1.450,1.163,1.881,1.277,0.910,4.956,1.339,1.937,6.825,7.271
min,18.000,1.000,1.920,0.500,44.000,3.500,1.000,0.000,0.000,0.000,1.000,0.000,1.000,0.000,0.000,56.000,60.000
25%,20.000,1.750,3.360,2.500,84.000,6.200,4.500,1.700,0.600,1.700,3.200,0.500,9.000,1.000,2.700,94.000,89.000
50%,23.000,3.000,3.710,3.500,93.000,7.000,5.800,2.800,1.500,3.000,4.100,1.200,12.000,2.000,4.000,100.000,95.000
75%,26.000,4.000,4.000,4.500,100.000,7.800,7.100,3.800,2.300,4.400,4.900,1.900,15.000,3.000,5.300,100.000,100.000
max,28.000,4.000,4.000,9.400,100.000,10.000,12.000,8.000,6.400,10.000,9.000,5.000,30.000,8.000,11.400,100.000,100.000

---

## EDA - Univariate Analysis

Next, we are going to perform exploratory analysis to explore our dataset, uncover hidden patterns, and get to know our dataset better.